# Generated by Django 6.0.6 on 2026-06-26 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
        ('request', '0004_alter_request_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='approval',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approval',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('director', 'Director'), ('finance', 'Finance'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='approval',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('request', 'role')},
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['request', 'order'], name='approval_ap_request_88a188_idx'),
        ),
    ]
