# Generated by Django 6.0.6 on 2026-06-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_release', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashrelease',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashrelease',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('released', 'Released'), ('completed', 'Completed'), ('flagged', 'Flagged')], default='pending', max_length=20),
        ),
    ]
