# Generated by Django 6.0.6 on 2026-06-30 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_release', '0002_cashrelease_amount_cashrelease_status'),
        ('receipt', '0002_receipt_amount_receipt_review_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='transaction',
        ),
        migrations.AddField(
            model_name='receipt',
            name='cash_release',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='cash_release.cashrelease'),
            preserve_default=False,
        ),
    ]
