# Generated by Django 6.0.6 on 2026-06-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('PHP', 'PHP'), ('OTHER', 'Other')], default='PHP', max_length=10),
        ),
        migrations.AddField(
            model_name='request',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='ext',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='request',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='payee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='payee_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('SUPPLIER', 'Supplier')], default='EMPLOYEE', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_method',
            field=models.CharField(choices=[('TT', 'T/T'), ('CASH', 'Cash')], default='TT', max_length=10),
        ),
        migrations.AddField(
            model_name='request',
            name='project_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_supervisor', 'Pending Supervisor'), ('pending_director', 'Pending Director'), ('pending_finance', 'Pending Finance'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
    ]
