# Generated by Django 6.0.6 on 2026-06-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_currency_request_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('pending_supervisor', 'Pending Supervisor'), ('pending_director', 'Pending Director'), ('pending_finance', 'Pending Finance'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
