# Generated by Django 6.0.6 on 2026-07-02 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='payee_name',
        ),
    ]
